services:
    imports:
        - { resource: twitter.conf.yml }
        - { resource: twitter.yml }

    newscoop_twitter_plugin.lifecyclesubscriber:
        class: Newscoop\TwitterPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_twitter_plugin.hooks.listener:
        class:     "Newscoop\TwitterPluginBundle\EventListener\HooksListener"
        arguments: ["@service_container"]
        tags:
          - { name: kernel.event_listener, event: newscoop_admin.interface.article.edit.sidebar, method: sidebar }
