imports:
    - { resource: twitter.conf.yml }
    - { resource: twitter.yml }

services:
    newscoop_twitter_plugin.lifecyclesubscriber:
        class: Newscoop\TwitterPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

